import type { SVGAttributes } from "react";

export interface SVGIconProps
  extends Omit<SVGAttributes<SVGElement>, "xmlns" | "viewBox"> {}

export { default as Alarm } from "./Alarm";
export { default as CaseMedical } from "./CaseMedical";
export { default as Clock } from "./Clock";
export { default as Lock } from "./Lock";
export { default as Mail } from "./Mail";
export { default as Recipe } from "./Recipe";
export { default as Search } from "./Search";
export { default as SquarePlus } from "./SquarePlus";
export { default as UserProfile } from "./UserProfile";
export { default as Health } from "./Health";
export { default as CaretDown } from "./CaretDown";
export { default as Arrow } from "./Arrow";
export { default as Plus } from "./Plus";
export { default as Eye } from "./Eye";
export { default as Pdf } from "./Pdf";
export { default as Receipt } from "./Receipt";
export { default as Medicine } from "./Medicine";
export { default as Alert } from "./Alert";
export { default as BriefCase } from "./BriefCase";
export { default as IdCard } from "./IdCard";
export { default as Droplet } from "./Droplet";
export { default as Pressure } from "./Pressure";
export { default as Frecuence } from "./Frecuence";
export { default as Temperature } from "./Temperature";
export { default as Weight } from "./Weight";
export { default as Size } from "./Size";
export { default as Error } from "./Error";
export { default as Check } from "./Check";
export { default as LightBulb } from "./LightBulb";
export { default as Home } from "./Home";
export { default as Date } from "./Date";
export { default as PaperClip } from "./PaperClip";
export { default as Stethoscope } from "./Stethoscope";
export { default as AngleUp } from "./AngleUp";
export { default as AngleDown } from "./AngleDown";
export { default as Logout } from "./Logout";
export { default as Xmark } from "./Xmark";
export { default as PenEdit } from "./PenEdit";
export { default as Trash } from "./Trash";
export { default as Password } from "./Password";
export { default as PasswordHidden } from "./PasswordHidden";
export { default as LoadingPing } from "./LoadingPing";
export { default as Circle } from "./Circle";
export { default as Print } from "./Print";
export { default as Menu } from "./Menu";
export { default as Bussiness } from "./Bussiness";
export { default as Doctor } from "./Doctor";
export { default as Microscope } from "./Microscope";
export { default as HandHeart } from "./HandHeart";
export { default as SaveDisk } from "./SaveDisk";
export { default as Box } from "./Box";
