export const colorCards = [
  {
    id: "1",
    title: "available",
    color: "green",
    valueApptm: "fill-available text-available border-available",
    valueBorder: "border-tertiary-available",
    valueTime: "bg-secondary-available fill-available text-available",
    shadow: "",
  },
  {
    id: "2",
    title: "late",
    color: "yellow",
    valueApptm: "fill-warning text-warning border-warning",
    valueBorder: "border-secondary-warning",
    valueTime: "bg-secondary-warning fill-warning text-warning",
    shadow: "",
  },
  {
    id: "3",
    title: "onTriageActive",
    color: "yellow",
    valueApptm: "fill-warning text-warning border-warning",
    valueBorder: "border-tertiary-warning",
    valueTime: "bg-secondary-warning fill-warning text-warning",
    shadow: "shadow-card shadow-warning ",
  },
  {
    id: "4",
    title: "onHold",
    color: "red",
    valueApptm: "fill-error text-error border-error",
    valueBorder: "border-error",
    valueTime: "bg-secondary-error fill-error text-error",
    shadow: "",
  },
  {
    id: "5",
    title: "onQueue",
    color: "gray",
    valueApptm:
      "fill-placeholder-color text-placeholder-color border-placeholder-color",
    valueBorder: "border-placeholder-color",
    valueTime: "bg-placeholder-color fill-white text-white",
    shadow: "",
  },
];
